### ISSUE TITLE
Log probabilities for discriminative models 

### ISSUE THREAD

**Issue by kere-nel** [moinnadeem/StereoSet#7]
Hi, it says on the paper that you compute the log probability for BERT/RoBERTa, but [here](https://github.com/moinnadeem/StereoSet/blob/master/code/eval_discriminative_models.py#L172) it seems like you're just taking the probabilities. Is this intentional?

**Comment by sivareddyg** [comment]
@Lynx1820 please raise this issue in the new repo (if the problem still exists). We made several changes https://github.com/McGill-NLP/bias-bench 

We are no longer maintaining this repo. See you in the other repo!

**Comment by ncmeade** [comment]
Closing this since it was resolved [here](https://github.com/McGill-NLP/bias-bench/issues/3).
